### PR TITLE
 Fix #1612: Remove unsupported script-inline from template and CSP buffer

### LINKED ISSUE #1612: Uncaught EvalError: call to Function() blocked by CSP in parseEventCallback
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set CSP header with eval denied
2. Load the page

## Expected behavior and actual behavior

When I follow those steps, I see console error:

    Uncaught EvalError: call to Function() blocked by CSP

    parseEventCallback fileinput.js:475
    stash fileinput.js:509
    each jQuery
    stash fileinput.js:506
    _createContainer fileinput.js:4746
    _init fileinput.js:982
    FileInput fileinput.js:742
    fileinput fileinput.js:5781
    jQuery 2
    fileinput fileinput.js:5769
    js fileinput.js:61

I was expecting to see fileinput loading up and run.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.3.1
- bootstrap version: 4.3.1
- bootstrap-fileinput version: 5.1.2

## Isolating the problem

- [x] This bug happens [on the plugin demos page](http://plugins.krajee.com/file-input/demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using bootstrap-fileinput without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
No, because I can not send header there.
But here I have an example: https://pastebin.com/9KC6yGtH

Problem was created with commit [aa99882](https://github.com/kartik-v/bootstrap-fileinput/commit/aa99882)
"Implement CSP compliance for HTML markup via templates fix #1565 fix #1571"

`Function()` is considered as [unsafe eval](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_eval_expressions) by CSP.

### PR DESCRIPTION
**Pull request by Kwaadpepper**
Since `Function()` is considered same as eval.
You cannot parse JS without triggering unsafe-eval.
There is no way to bypass this either you force unsafe-inline, unsafe-eval or just disable JS inline event from templates.

The third option seems to be the only solution.

Also your site would need to be updated to remove inline-script (onpaste ..)
https://plugins.krajee.com/file-input/plugin-options

## Scope
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

## Changes
The following changes were made

- remove inline script form template (caption name)
- disable click and paste with jquery event ( return false ) instead of inline script from template
- remove inline-script from CSP buffer

## Related Issues
#1612

### CODE REVIEW

**Comment by kartik-v** [comment]
Looks good - just one thing... we could trigger the `onpaste` and `onkeydown` event to supress that behavior on the `file-caption-name` after every time the template is loaded on the DOM...  so this PR change looks good... once we do the above change.

File: js/fileinput.js [hunk 1]
```diff
@@ -1027,6 +1003,8 @@
             if (self.hideThumbnailContent) {
                 $h.addCss(self.$preview, 'hide-content');
             }
+            $cont.find('.file-caption-name').on('keydown', function () { return false; })
```
Comment (Kwaadpepper) [inline js/fileinput.js:1006]: This handles `onkeydown` and `onpaste` event while `bootstrap-fileinput` is loaded on the DOM since it is in `FileInput.prototype._init` function.

Did I miss something ?

**Comment by Kwaadpepper** [comment]
> Looks good - just one thing... we could trigger the `onpaste` and `onkeydown` event to supress that behavior on the `file-caption-name` after every time the template is loaded on the DOM... so this PR change looks good... once we do the above change.

I just saw a better suited place to register these two events.

**Comment by kartik-v** [comment]
It's ok on init... But i think the templates are used to overwrite the content in the DOM time to time. But I think that happens mainly for file selections, initial preview and uploads and deletes. The caption probably is overrwritten then so the events may get killed. 

Need to check appropriate place for that.

**Comment by Kwaadpepper** [comment]
Well, I have tested in my end enabling file caption I have not seen that file caption been destroyed at any time event is still present. Only file preview are added and removed when browsing files.

The other solution could be to add the event on the plug-in root node using the third parameter of jQuery `$('rootnode')on('keydown', 'filecaption', function() { return false; })`

**Comment by kartik-v** [comment]
Its fine ... the `_refreshContainer` method for some use case will overwrite the entire container HTML (when someone uses the refresh method of the plugin). I think we may need to change event handlers init accordingly.

**Comment by Kwaadpepper** [comment]
Oh, I see, the entire DOM is re-injected with `$h.setHtml($container, self._renderMain());`  in 4736

But if you look at setHtml `$elem` is never reassigned.
So it's a bug as you said event events would be removed (or lost in a memory leak).

I guess the `_listen` method would have to register all events. It would also need to unbind previous events.
Maybe a helper method to bind events would be handy.

**Comment by Kwaadpepper** [comment]
Ok I just investigated the refresh method. And for what I see things are all ready correctly handled.

`_refresh` method will call `self._listen();`  So events are re-binded when DOM is refreshed.

`self._handler` is called to bind an event, so it will prevent the binding of the same event multiple times.

moreover, I tested the refresh function with my patch and caption events are there and seems to be working.
(tested with `$('#uploadInput').fileinput('refresh')` )

**Comment by kartik-v** [comment]
Thanks if you have tested it... looks good then. Could you also submit the minified JS (you can [minify it from this site](https://refresh-sf.com/)) ... will merge the PR then.
